name: Deploy Fastify App

on:
  push:
    branches: ['master'] # ganti 'main' kalau perlu
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "📁 Go to project"
            cd /srv/backend

            echo "🔄 Pull latest code"
            git pull

            echo "📦 Install dependencies"
            npm install --production

            echo "🏗 Build TypeScript"
            npm run build

            echo "🚀 Start / Restart PM2 with 300MB RAM limit"
            if pm2 describe backend > /dev/null; then
              echo "🔁 Restart existing service"
              pm2 restart backend --max-memory-restart 300M
            else
              echo "✨ Create new service"
              pm2 start npm --name backend --max-memory-restart 300M -- start
            fi

            echo "💾 Save PM2 state"
            pm2 save

            echo "✅ DONE"
